In [ ]:
import numpy as np

# 1.数据类型

In [ ]:
# 类型字段名可以用于存取实际的 age 列
import numpy as np
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

In [ ]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a3 = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

# 2.array 创建数组

array()函数，括号内可以是列表、元祖、数组、生成器

arange()，类似range()，在给定的间隔内返回均匀间隔的值

linespace()，返回在间隔上（前闭后闭）计算的num个均匀间隔的样本

zeros()/zeros_like()/ones()/ones_like()

eye(n)，创建一个正方的N*N矩阵，对角线值为1，其余为0

In [ ]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

In [ ]:
#元组
a = np.array([1,2,3,4,5])

b = np.array(a)

b

In [ ]:
# 迭代对象
np.array(range(10))

In [ ]:
#生成器
np.array([i**2 for i in range(10)]) # i**2 是取平方

练习1 ： 创建 10 以内的偶数的数组

In [ ]:
np.array(range(2,11,2))
#np.array([i for i in range(10) if i%2 == 0])

In [ ]:
# 列表中元素类型不相同
ar3 = np.array([[1,2,3],
                ('a','b','c')
                ]) # 二维数组，嵌套序列（列表、元组均可）

ar3

ar4 = np.array([[1,2,3],('a','b','c','d')])
ar4

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)  # 看维度
a.shape=(2,3)  # 维度改为二行三列
print(a)

print(a * 3 )  # 数组运算

print(a > 3)  # 将数组中的元素 都与 3 进行比较

In [ ]:
import numpy as np
c = np.arange(1,19)
c.shape = (3,2,3) #(页，行，列)
print(c)

### zeros(数组元素个数)

In [ ]:
import numpy as np 
a = np.zeros(10)
print(a)

b = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(b)

## np.zeros(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.zeros(10)
print(a)

## np.ones(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.ones(10)
print(a)

## arange

In [ ]:
import numpy as np
print(np.arange(10))    # 返回0-9，整型
print(np.arange(10.0))  # 返回0.0-9.0，浮点型
print(np.arange(5,12))  # 返回5-11
print(np.arange(5.0,12,2))  # 返回5.0-12.0，步长为2

## linspace()
返回在间隔(开始，停止)上计算的num个均匀间隔的样本

numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None) 

In [ ]:

import numpy as np
ar1 = np.linspace(2.0, 3.0, num=5)
ar2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
ar3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(ar1,type(ar1))
print(ar2)
print(ar3,type(ar3))

## ndarray 对象属性的基本操作

### 1. 数组的维度 ： np.ndarray.shape

In [ ]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.shape)

# 二维数组

ary1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(type(ary1),ary1,ary1.shape)

### 2. 元素的类型 np.ndarray.dtype

In [ ]:
import numpy as np
ary3 = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.dtype)

# 转换ary 元素的类型

ary4 = ary.astype(float)
print(type(ary4),ary4,ary4.dtype)

ary5 = ary.astype(str)
print(type(ary5),ary5,ary5.dtype)

### 数组元素的个数：np.ndarray.size

In [ ]:
import numpy as np
ary2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# 观察维度，size, len 的区别
print(ary2.shape,ary2.size,len(ary2))

### 数组元素索引（下标）
数组对象[..., 页号,行号,列号]

下标从 0 开始，到数组len-1结束

## 维度基础操作

In [ ]:
import numpy as np
a = np.arange(1,9)

## 自定义复合类型

In [ ]:
import numpy as np 
data=[
    ('zs',[90,80,85],15),
    ('ls',[92,81,83],16),
    ('ww',[95,85,85],15)
]
# 第一种设置dtype的方式
a = np.array(data, dtype='U3,3int32,int32')
# print(a)
# print(a[0]['f0'],":",a[1]['f1'])
# print("==========")

# 第二种
b = np.array(data,dtype=[('name','str',2),
                         ('scores','int32',3),
                         ('age','int32',1)
                         ])

# print(b)
# print(b[2]['age'])


# 第三种
c = np.array(data,dtype={
    'names':['name','scores','age'],
    'formats':['U2','3int32','int32']
})

print(c)
print(c[1]['name'])

In [ ]:
import numpy as np
a = np.array([10,20,30],dtype=[('age',np.int8)])
b = np.array([(10),(20),(30)],dtype=[('age',np.int8)])
print(a)
print(a['age'])
print(a['age'][1])
print(b)
print(b['age'])
print(b['age'][0])

# 2.维度操作
## （1）视图变维 （数据共享）
## reshape() 和 ravel()

In [ ]:
import numpy as np

a = np.arange(1,9)
print(a) # p[1,2,3,4,5,6,7,8]
b = a.reshape(2,4) # 视图变维，变为2 行 4 列的二维数组
print(b)
c = b.reshape(2,2,2)  # 视图变维，变为2 页 2 行 2 列的三维数组
print("====")
print(c)
print("====")
d = c.ravel()  # 变为 1 维数组
print(d)

In [ ]:
import numpy as np
a = np.arange(1,10)
print(a, a.shape)

# 复制变维
b = a. flatten()
print(b,'->b')
print("=====数据独立后原修改不影响新的=====")
a[0]= 88
print(a)
print(b)

### numpy.ndarray.flat 

是一个数组元素迭代器


In [93]:
import numpy as np
 
a = np.arange(9).reshape(3,3) 
print ('原始数组：')
for row in a:
    print (row)
 
#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print ('迭代后的数组：')
for element in a.flat:
    print (element)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组：
0
1
2
3
4
5
6
7
8


## 2. 翻转数组


In [94]:
# transpose(arr,axes)

import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (np.transpose(a))

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [95]:
# numpy.rollaxis

import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('获取数组中一个值：')
print(np.where(a==6))   
print(a[1,1,0])  # 为 6
print ('\n')
 
 
# 将轴 2 滚动到轴 0（宽度到深度）
 
print ('调用 rollaxis 函数：')
b = np.rollaxis(a,2,0)
print (b)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [0, 1, 1]
# 最后一个 0 移动到最前面
print(np.where(b==6))   
print ('\n')
 
# 将轴 2 滚动到轴 1：（宽度到高度）
 
print ('调用 rollaxis 函数：')
c = np.rollaxis(a,2,1)
print (c)
# 查看元素 a[1,1,0]，即 6 的坐标，变成 [1, 0, 1]
# 最后的 0 和 它前面的 1 对换位置
print(np.where(c==6))   
print ('\n')

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
获取数组中一个值：
(array([1]), array([1]), array([0]))
6


调用 rollaxis 函数：
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
(array([0]), array([1]), array([1]))


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
(array([1]), array([0]), array([1]))




In [97]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
 
print ('调用 swapaxes 函数后的数组：')
print (np.swapaxes(a, 2, 0))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用 swapaxes 函数后的数组：
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


## 切片操作

### 1. 一维数组

In [ ]:
import numpy as np
a = np.arange(1,10)
print(a) # 123456789
print(a[:3]) # 123
print(a[3:6]) # 456
print(a[6:]) # 789
print(a[::-1]) #987654321
print(a[:-4:-1]) #987
print(a[-4:-7:-1]) #654
print(a[-7::-1]) # 321

### 2. 多维数组

二维数组切片： 数组对象[行操作,列操作]

多维：数组对象[1维度,2维度,3维度]

In [ ]:
import numpy as np
a = np.arange(1,10)
a.resize(3,3) # 更改数组的维度
print(a)
print(a[:2,:2]) # 拿到 12 行，12 列
print(a[::2,::2]) # 拿到 13 行，13 列

In [ ]:
import numpy as np
a = np.arange(1,28)
a.resize(3,3,3)
print(a)

print("======")
# 切出 1 页
print("切出 1 页")
print(a[0,:,:])

# 切出 所有页的第一行
print("所有页的第一行")
print(a[:,1,:])

# 切出 0 页的 1 行 1 列
print("切出 0 页的 1 行 1 列")
print(a[0,:,1])

### 布尔索引

In [ ]:
# 获取大于 5 的元素

import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print ('我们的数组是：')
print (x)
print ('\n')
# 打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

### 花式索引（利用整数数组）

#### 1. 一维数组

In [ ]:
import numpy as np

x = np.arange(9)
print(x)
# 一维数组读取指定下标对应的元素
print("-------读取下标对应的元素-------")
x2 = x[[0, 6]] # 使用花式索引
print(x2)

print(x2[0])
print(x2[1])

#### 2. 二维数组

`print(x[[数字]])` 输出对应下标所在的行「下标从 0 开始」

In [ ]:
# 顺序存储
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print(x)
# 二维数组读取指定下标对应的行
print("-------读取下标对应的行-------")
print (x[[4,2,1,7]])

In [ ]:
# 倒序索引
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[[-4,-2,-1,-7]])

In [ ]:
# 传入多个索引数组 要使用np.ix_

import numpy as np 
 
x=np.arange(32).reshape((8,4))
print(x)
print("======")
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

### 掩码操作

In [ ]:
import numpy as np
a = np.arange(1,10)
mask =[True,False,True,False,True,False,True,False,True]
print(a[mask])

In [ ]:
"""mask掩码 100 的三倍数"""
import numpy as np
a = np.arange(1,100)
# print(a[a%3 == 0])
mask = a%3 == 0 # mask 为 True 和 False 的数组
print(a[mask])

In [ ]:
import numpy as np
names = np.array(['apple','Mate30','mi','oppo','vivo'])
rank = [1,0,3,4,2]
print(names[rank])

## 数组操作

### 1. 垂直方向

In [ ]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(a)
print(b)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a,b))
print(c)
# 垂直方向完成拆分操作，生成两个数组
d,e=np.vsplit(c,2)  # 拆几个 就需要用几个变量来进行接受

### 2. 水平方向

In [ ]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

#水平方向
c = np.hstack((a,b))
print(c)
d,e = np.hsplit(c,2)

### 3. 深度方向操作

In [ ]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
#深度方向
i = np.dstack((a,b))
print(i)
d,e = np.dsplit(c,2)

### 迭代数组

NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。

迭代器最基本的任务的可以完成对数组元素的访问。

接下来我们使用 arange() 函数创建一个 2X3 数组，并使用 nditer 对它进行迭代。

In [91]:
import numpy as np
 
a = np.arange(6).reshape(2,3)
print ('原始数组是：')
print (a)
print ('\n')
print ('迭代输出元素：')
for x in np.nditer(a):
    print (x, end=", " )
print ('\n')


原始数组是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0, 1, 2, 3, 4, 5, 



In [88]:
# for x in np.nditer(a, order='F'):Fortran order，即是列序优先
# for x in np.nditer(a.T, order='C'):C order，即是行序优先 

import numpy as np
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：') 
print (a) 
print ('\n') 
print ('原始数组的转置是：') 
b = a.T 
print (b) 
print ('\n') 
print ('以 C 风格顺序排序：') 
c = b.copy(order='C')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )
print  ('\n') 
print  ('以 F 风格顺序排序：')
c = b.copy(order='F')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以 C 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以 F 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [90]:
import numpy as np
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
for x in np.nditer(a, op_flags=['readwrite']): 
    x[...]=2*x 
print ('修改后的数组是：')
print (a)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


### 使用外部循环
nditer 类的构造器拥有 flags 参数，它可以接受下列值：

参数	             描述
c_index	            可以跟踪 C 顺序的索引
f_index	            可以跟踪 Fortran 顺序的索引
multi_index	        每次迭代可以跟踪一种索引类型
external_loop	    给出的值是具有多个值的一维数组，而不是零维数组

In [89]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：')
print (a)
print ('\n')
print ('修改后的数组是：')
for x in np.nditer(a, flags =  ['external_loop'], order =  'F'):  
   print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是：
[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 

### 广播迭代

In [92]:
import numpy as np 
 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 

## 数组计算

### 1. 广播 broadcast

In [ ]:
import numpy as np 
 
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

In [ ]:
# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制
import numpy as np 
 
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)

In [107]:
import numpy as np
 
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])  
 
# 对 y 广播 x
b = np.broadcast(x,y)  
# 它拥有 iterator 属性，基于自身组件的迭代器元组
 
print ('对 y 广播 x：')
r,c = b.iters
 
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))
print ('\n')
# shape 属性返回广播对象的形状
 
print ('广播对象的形状：')
print (b.shape)
print ('\n')
# 手动使用 broadcast 将 x 与 y 相加
b = np.broadcast(x,y)
c = np.empty(b.shape)
 
print ('手动使用 broadcast 将 x 与 y 相加：')
print (c.shape)
print ('\n')
c.flat = [u + v for (u,v) in b]
 
print ('调用 flat 函数：')
print (c)
print ('\n')
# 获得了和 NumPy 内建的广播支持相同的结果
 
print ('x 与 y 的和：')
print (x + y)

对 y 广播 x：
1 4
1 5


广播对象的形状：
(3, 3)


手动使用 broadcast 将 x 与 y 相加：
(3, 3)


调用 flat 函数：
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 连接数组


In [108]:
# numpy.concatenate
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
# 两个数组的维度相同
 
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
print ('\n')
 
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [109]:
# stack
import numpy as np
 
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)
print ('\n')
b = np.array([[5,6],[7,8]])
 
print ('第二个数组：')
print (b)
print ('\n')
 
print ('沿轴 0 堆叠两个数组：')
print (np.stack((a,b),0))
print ('\n')
 
print ('沿轴 1 堆叠两个数组：')
print (np.stack((a,b),1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿轴 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
