In [ ]:
import numpy as np

## array 创建数组

In [ ]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

In [ ]:
#元组
a = np.array([1,2,3,4,5])

b = np.array(a)

b

In [ ]:
# 迭代对象
np.array(range(10))

In [ ]:
#生成器
np.array([i**2 for i in range(10)]) # i**2 是取平方

练习1 ： 创建 10 以内的偶数的数组

In [ ]:
np.array(range(2,11,2))
#np.array([i for i in range(10) if i%2 == 0])

In [ ]:
# 列表中元素类型不相同
ar3 = np.array([[1,2,3],
                ('a','b','c')
                ]) # 二维数组，嵌套序列（列表、元组均可）

ar3

In [ ]:
ar4 = np.array([[1,2,3],('a','b','c','d')])
ar4

In [33]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)  # 看维度
a.shape=(2,3)  # 维度改为二行三列
print(a)

print(a * 3 )  # 数组运算

print(a > 3)  # 将数组中的元素 都与 3 进行比较

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
[[ 3  6  9]
 [12 15 18]]
[[False False False]
 [ True  True  True]]
