In [ ]:
import numpy as np

# 1.数据类型

In [ ]:
# 类型字段名可以用于存取实际的 age 列
import numpy as np
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

In [ ]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a3 = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

# 2.array 创建数组

array()函数，括号内可以是列表、元祖、数组、生成器

arange()，类似range()，在给定的间隔内返回均匀间隔的值

linespace()，返回在间隔上（前闭后闭）计算的num个均匀间隔的样本

zeros()/zeros_like()/ones()/ones_like()

eye(n)，创建一个正方的N*N矩阵，对角线值为1，其余为0

In [ ]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

In [ ]:
#元组
a = np.array([1,2,3,4,5])

b = np.array(a)

b

In [ ]:
# 迭代对象
np.array(range(10))

In [ ]:
#生成器
np.array([i**2 for i in range(10)]) # i**2 是取平方

练习1 ： 创建 10 以内的偶数的数组

In [4]:
np.array(range(2,11,2))
#np.array([i for i in range(10) if i%2 == 0])

array([ 2,  4,  6,  8, 10])

In [ ]:
# 列表中元素类型不相同
ar3 = np.array([[1,2,3],
                ('a','b','c')
                ]) # 二维数组，嵌套序列（列表、元组均可）

ar3

ar4 = np.array([[1,2,3],('a','b','c','d')])
ar4

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)  # 看维度
a.shape=(2,3)  # 维度改为二行三列
print(a)

print(a * 3 )  # 数组运算

print(a > 3)  # 将数组中的元素 都与 3 进行比较

In [5]:
import numpy as np
c = np.arange(1,19)
c.shape = (3,2,3) #(页，行，列)
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


### zeros(数组元素个数)

In [77]:
import numpy as np 
a = np.zeros(10)
print(a)

b = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## np.zeros(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.zeros(10)
print(a)

## np.ones(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.ones(10)
print(a)

## arange

In [2]:
import numpy as np
print(np.arange(10))    # 返回0-9，整型
print(np.arange(10.0))  # 返回0.0-9.0，浮点型
print(np.arange(5,12))  # 返回5-11
print(np.arange(5.0,12,2))  # 返回5.0-12.0，步长为2

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11]
[ 5.  7.  9. 11.]


## linspace()
返回在间隔(开始，停止)上计算的num个均匀间隔的样本

numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None) 

In [3]:

import numpy as np
ar1 = np.linspace(2.0, 3.0, num=5)
ar2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
ar3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(ar1,type(ar1))
print(ar2)
print(ar3,type(ar3))

[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'>
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


## ndarray 对象属性的基本操作

### 1. 数组的维度 ： np.ndarray.shape

In [ ]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.shape)

# 二维数组

ary1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(type(ary1),ary1,ary1.shape)

### 2. 元素的类型 np.ndarray.dtype

In [ ]:
import numpy as np
ary3 = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.dtype)

# 转换ary 元素的类型

ary4 = ary.astype(float)
print(type(ary4),ary4,ary4.dtype)

ary5 = ary.astype(str)
print(type(ary5),ary5,ary5.dtype)

### 数组元素的个数：np.ndarray.size

In [52]:
import numpy as np
ary2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# 观察维度，size, len 的区别
print(ary2.shape,ary2.size,len(ary2))

(2, 4) 8 2


### 数组元素索引（下标）
数组对象[..., 页号,行号,列号]

下标从 0 开始，到数组len-1结束

## 维度基础操作

In [ ]:
import numpy as np
a = np.arange(1,9)

## 自定义复合类型

In [16]:
import numpy as np 
data=[
    ('zs',[90,80,85],15),
    ('ls',[92,81,83],16),
    ('ww',[95,85,85],15)
]
# 第一种设置dtype的方式
a = np.array(data, dtype='U3,3int32,int32')
# print(a)
# print(a[0]['f0'],":",a[1]['f1'])
# print("==========")

# 第二种
b = np.array(data,dtype=[('name','str',2),
                         ('scores','int32',3),
                         ('age','int32',1)
                         ])

# print(b)
# print(b[2]['age'])


# 第三种
c = np.array(data,dtype={
    'names':['name','scores','age'],
    'formats':['U2','3int32','int32']
})

print(c)
print(c[1]['name'])

[('zs', [90, 80, 85], 15) ('ls', [92, 81, 83], 16)
 ('ww', [95, 85, 85], 15)]
ls


/var/folders/sx/pzbm52bx4p3gxcw4dtx_frfh0000gn/T/ipykernel_70845/470386524.py:14: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  b = np.array(data,dtype=[('name','str',2),


In [27]:
import numpy as np
a = np.array([10,20,30],dtype=[('age',np.int8)])
b = np.array([(10),(20),(30)],dtype=[('age',np.int8)])
print(a)
print(a['age'])
print(a['age'][1])
print(b)
print(b['age'])
print(b['age'][0])

[(10,) (20,) (30,)]
[10 20 30]
20
[(10,) (20,) (30,)]
[10 20 30]
10


# 2.维度操作
## （1）视图变维 （数据共享）
## reshape() 和 ravel()

In [35]:
import numpy as np

a = np.arange(1,9)
print(a) # p[1,2,3,4,5,6,7,8]
b = a.reshape(2,4) # 视图变维，变为2 行 4 列的二维数组
print(b)
c = b.reshape(2,2,2)  # 视图变维，变为2 页 2 行 2 列的三维数组
print("====")
print(c)
print("====")
d = c.ravel()  # 变为 1 维数组
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
====
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
====
[1 2 3 4 5 6 7 8]


In [42]:
import numpy as np
a = np.arange(1,10)
print(a, a.shape)

# 复制变维
b = a. flatten()
print(b,'->b')
print("=====数据独立后原修改不影响新的=====")
a[0]= 88
print(a)
print(b)

[1 2 3 4 5 6 7 8 9] (9,)
[1 2 3 4 5 6 7 8 9] ->b
=====数据独立后原修改不影响新的=====
[88  2  3  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]


## 切片操作

### 1. 一维数组

In [50]:
import numpy as np
a = np.arange(1,10)
print(a) # 123456789
print(a[:3]) # 123
print(a[3:6]) # 456
print(a[6:]) # 789
print(a[::-1]) #987654321
print(a[:-4:-1]) #987
print(a[-4:-7:-1]) #654
print(a[-7::-1]) # 321

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6]
[7 8 9]
[9 8 7 6 5 4 3 2 1]
[9 8 7]
[6 5 4]
[3 2 1]


### 2. 多维数组

二维数组切片： 数组对象[行操作,列操作]

多维：数组对象[1维度,2维度,3维度]

In [53]:
import numpy as np
a = np.arange(1,10)
a.resize(3,3) # 更改数组的维度
print(a)
print(a[:2,:2]) # 拿到 12 行，12 列
print(a[::2,::2]) # 拿到 13 行，13 列

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 3]
 [7 9]]


In [63]:
import numpy as np
a = np.arange(1,28)
a.resize(3,3,3)
print(a)

print("======")
# 切出 1 页
print("切出 1 页")
print(a[0,:,:])

# 切出 所有页的第一行
print("所有页的第一行")
print(a[:,1,:])

# 切出 0 页的 1 行 1 列
print("切出 0 页的 1 行 1 列")
print(a[0,:,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
切出 1 页
[[1 2 3]
 [4 5 6]
 [7 8 9]]
所有页的第一行
[[ 4  5  6]
 [13 14 15]
 [22 23 24]]
切出 0 页的 1 行 1 列
[2 5 8]


### 布尔索引

In [78]:
# 获取大于 5 的元素

import numpy as np
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print ('我们的数组是：')
print (x)
print ('\n')
# 打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


### 花式索引（利用整数数组）

#### 1. 一维数组

In [79]:
import numpy as np

x = np.arange(9)
print(x)
# 一维数组读取指定下标对应的元素
print("-------读取下标对应的元素-------")
x2 = x[[0, 6]] # 使用花式索引
print(x2)

print(x2[0])
print(x2[1])

[0 1 2 3 4 5 6 7 8]
-------读取下标对应的元素-------
[0 6]
0
6


#### 2. 二维数组

`print(x[[数字]])` 输出对应下标所在的行「下标从 0 开始」

In [80]:
# 顺序存储
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print(x)
# 二维数组读取指定下标对应的行
print("-------读取下标对应的行-------")
print (x[[4,2,1,7]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-------读取下标对应的行-------
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


In [81]:
# 倒序索引
import numpy as np 
 
x=np.arange(32).reshape((8,4))
print (x[[-4,-2,-1,-7]])

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [83]:
# 传入多个索引数组 要使用np.ix_

import numpy as np 
 
x=np.arange(32).reshape((8,4))
print(x)
print("======")
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### 掩码操作

In [66]:
import numpy as np
a = np.arange(1,10)
mask =[True,False,True,False,True,False,True,False,True]
print(a[mask])

[1 3 5 7 9]


In [68]:
"""mask掩码 100 的三倍数"""
import numpy as np
a = np.arange(1,100)
# print(a[a%3 == 0])
mask = a%3 == 0 # mask 为 True 和 False 的数组
print(a[mask])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [70]:
import numpy as np
names = np.array(['apple','Mate30','mi','oppo','vivo'])
rank = [1,0,3,4,2]
print(names[rank])

['Mate30' 'apple' 'oppo' 'vivo' 'mi']


## 数组操作

### 1. 垂直方向

In [72]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
print(a)
print(b)
# 垂直方向完成组合操作，生成新数组
c = np.vstack((a,b))
print(c)
# 垂直方向完成拆分操作，生成两个数组
d,e=np.vsplit(c,2)  # 拆几个 就需要用几个变量来进行接受

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 2. 水平方向

In [73]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)

#水平方向
c = np.hstack((a,b))
print(c)
d,e = np.hsplit(c,2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### 3. 深度方向操作

In [75]:
import numpy as np 
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(2,3)
#深度方向
i = np.dstack((a,b))
print(i)
d,e = np.dsplit(c,2)

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
