In [ ]:
import numpy as np

# 1.数据类型

In [ ]:
# 类型字段名可以用于存取实际的 age 列
import numpy as np
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a['age'])

In [ ]:
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a3 = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(a)

# 2.array 创建数组

array()函数，括号内可以是列表、元祖、数组、生成器

arange()，类似range()，在给定的间隔内返回均匀间隔的值

linespace()，返回在间隔上（前闭后闭）计算的num个均匀间隔的样本

zeros()/zeros_like()/ones()/ones_like()

eye(n)，创建一个正方的N*N矩阵，对角线值为1，其余为0

In [ ]:
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

In [ ]:
#元组
a = np.array([1,2,3,4,5])

b = np.array(a)

b

In [ ]:
# 迭代对象
np.array(range(10))

In [ ]:
#生成器
np.array([i**2 for i in range(10)]) # i**2 是取平方

练习1 ： 创建 10 以内的偶数的数组

In [4]:
np.array(range(2,11,2))
#np.array([i for i in range(10) if i%2 == 0])

array([ 2,  4,  6,  8, 10])

In [ ]:
# 列表中元素类型不相同
ar3 = np.array([[1,2,3],
                ('a','b','c')
                ]) # 二维数组，嵌套序列（列表、元组均可）

ar3

ar4 = np.array([[1,2,3],('a','b','c','d')])
ar4

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a.shape)  # 看维度
a.shape=(2,3)  # 维度改为二行三列
print(a)

print(a * 3 )  # 数组运算

print(a > 3)  # 将数组中的元素 都与 3 进行比较

In [5]:
import numpy as np
c = np.arange(1,19)
c.shape = (3,2,3) #(页，行，列)
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


## np.zeros(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.zeros(10)
print(a)

## np.ones(数组元素个数，dtype='类型')

In [ ]:
import numpy as np
a = np.ones(10)
print(a)

## arange

In [2]:
import numpy as np
print(np.arange(10))    # 返回0-9，整型
print(np.arange(10.0))  # 返回0.0-9.0，浮点型
print(np.arange(5,12))  # 返回5-11
print(np.arange(5.0,12,2))  # 返回5.0-12.0，步长为2

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11]
[ 5.  7.  9. 11.]


## linspace()
返回在间隔(开始，停止)上计算的num个均匀间隔的样本

numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None) 

In [3]:

import numpy as np
ar1 = np.linspace(2.0, 3.0, num=5)
ar2 = np.linspace(2.0, 3.0, num=5, endpoint=False)
ar3 = np.linspace(2.0, 3.0, num=5, retstep=True)
print(ar1,type(ar1))
print(ar2)
print(ar3,type(ar3))

[2.   2.25 2.5  2.75 3.  ] <class 'numpy.ndarray'>
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


## ndarray 对象属性的基本操作

### 1. 数组的维度 ： np.ndarray.shape

In [ ]:
import numpy as np
ary = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.shape)

# 二维数组

ary1 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(type(ary1),ary1,ary1.shape)

### 2. 元素的类型 np.ndarray.dtype

In [ ]:
import numpy as np
ary3 = np.array([1,2,3,4,5,6])
print(type(ary),ary,ary.dtype)

# 转换ary 元素的类型

ary4 = ary.astype(float)
print(type(ary4),ary4,ary4.dtype)

ary5 = ary.astype(str)
print(type(ary5),ary5,ary5.dtype)

### 数组元素的个数：np.ndarray.size

In [52]:
import numpy as np
ary2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# 观察维度，size, len 的区别
print(ary2.shape,ary2.size,len(ary2))

(2, 4) 8 2


### 数组元素索引（下标）
数组对象[..., 页号,行号,列号]

下标从 0 开始，到数组len-1结束

## 维度基础操作

In [ ]:
import numpy as np
a = np.arange(1,9)